name: 'Close stale PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale PRs
        uses: actions/stale@v9
        with:
          days-before-issue-close: -1
          days-before-stale: 30
          exempt-assignees: 'iTitus, Segelzwerg'
          exempt-draft-pr: true
